server.port=8081
user.service.message=User Service is running from Config Server
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

spring.datasource.username=root
spring.datasource.password={cipher}546e9013b1d1df943dea79be83e75b00fc291b25e37024c047131dace1ad7fa7
